services:
  web:
    build: .
    container_name: pcb-detection-api
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-defaultsecretkey}
      - FLASK_ENV=production
      - MODEL_PATH=models/model.tflite
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./logs:/app/logs
      - ./models:/app/models:ro
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: pcb-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
    depends_on:
      - web
    restart: unless-stopped